// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJztXOXC2hMHZ4cXDsQKb4u_fNEaG6_AU',
    appId: '1:1012085303638:web:361a343eaab2bc209acef7',
    messagingSenderId: '1012085303638',
    projectId: 'lab3-joke-project',
    authDomain: 'lab3-joke-project.firebaseapp.com',
    storageBucket: 'lab3-joke-project.firebasestorage.app',
    measurementId: 'G-HDRFFQVHB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8JEFygD5zzCPjgob2iJD47kKMSULBeg',
    appId: '1:1012085303638:android:a62b11909dfbbbc89acef7',
    messagingSenderId: '1012085303638',
    projectId: 'lab3-joke-project',
    storageBucket: 'lab3-joke-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNTGtUn2ohRYMZ9V6P4mebYJ3IJN9S_o',
    appId: '1:1012085303638:ios:eed91edb91794ef49acef7',
    messagingSenderId: '1012085303638',
    projectId: 'lab3-joke-project',
    storageBucket: 'lab3-joke-project.firebasestorage.app',
    iosBundleId: 'com.example.randomJokesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNTGtUn2ohRYMZ9V6P4mebYJ3IJN9S_o',
    appId: '1:1012085303638:ios:eed91edb91794ef49acef7',
    messagingSenderId: '1012085303638',
    projectId: 'lab3-joke-project',
    storageBucket: 'lab3-joke-project.firebasestorage.app',
    iosBundleId: 'com.example.randomJokesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJztXOXC2hMHZ4cXDsQKb4u_fNEaG6_AU',
    appId: '1:1012085303638:web:7df9f0a83c86fb5e9acef7',
    messagingSenderId: '1012085303638',
    projectId: 'lab3-joke-project',
    authDomain: 'lab3-joke-project.firebaseapp.com',
    storageBucket: 'lab3-joke-project.firebasestorage.app',
    measurementId: 'G-PQ1FXJG81W',
  );
}
